name: Bot Runner

on:
  schedule:
    - cron: '0 4 * * *'   # 7:00 AM EAT
    - cron: '0 7 * * *'   # 10:00 AM EAT
    - cron: '0 10 * * *'  # 1:00 PM EAT
    - cron: '0 13 * * *'  # 4:00 PM EAT
    - cron: '0 16 * * *'  # 7:00 PM EAT
    - cron: '0 19 * * *'  # 10:00 PM EAT
  workflow_dispatch:

jobs:
  run_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        # Process pending users
        PYTHONPATH=src python -c "from database import process_pending_users; process_pending_users()"
        
        # Run bot for 2 hours
        python src/main.py &
        sleep 7200
        kill $!
        
        # Send appropriate sleep notification
        if [ $(date +%H) -eq 22 ]; then
          python src/sleep_notifier.py night
        else
          python src/sleep_notifier.py break
        fi
        
        # Take break
        sleep 3600
