name: Bot Runner
on:
  schedule:
    - cron: '0 4 * * *'   # 7:00 AM EAT
    - cron: '0 7 * * *'   # 10:00 AM EAT
    - cron: '0 10 * * *'  # 1:00 PM EAT
    - cron: '45 14 * * *'  # 4:00 PM EAT
    - cron: '0 16 * * *'  # 7:00 PM EAT
    - cron: '0 19 * * *'  # 10:00 PM EAT
  workflow_dispatch:

jobs:
  bot:
    name: Run Telegram Bot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run Bot
        env:
          PYTHONPATH: src
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE_NUMBER: ${{ secrets.TELEGRAM_PHONE_NUMBER }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          python src/main.py &
          sleep 7200  # Run for 2 hours
          kill $!
