name: Send User Updates

on:
  schedule:
    - cron: '10 5 * * *'   # 8:10 AM EAT
    - cron: '10 14 * * *'  # 4:10 PM EAT
    - cron: '10 21 * * *'  # 12:10 AM EAT
  workflow_dispatch:

jobs:
  send_updates:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Send updates to users
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python src/send_updates.py
