name: Send User Updates
on:
  schedule:
    - cron: '10 5 * * *'   # 8:10 AM EAT
    - cron: '50 14 * * *'  # 4:10 PM EAT
    - cron: '10 21 * * *'  # 12:10 AM EAT
  workflow_dispatch:

jobs:
  send:
    name: Send Updates to Users
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Keep workflow active
        run: |
          date > last_send.txt
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add last_send.txt
          git commit -m "Update last send timestamp"
          git push
      - name: Send Updates
        env:
          PYTHONPATH: src
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_API_ID: ${{ secrets.TELEGRAM_API_ID }}
          TELEGRAM_API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          TELEGRAM_PHONE_NUMBER: ${{ secrets.TELEGRAM_PHONE_NUMBER }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/send_updates.py
